# Generated by Django 4.2.2 on 2023-06-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='roles',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('C', 'Cliente'), ('A', 'Administrador')], default='Cliente', max_length=5),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='hora',
            field=models.TimeField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
